### ISSUE TITLE
phc-win release 2.0.1, EVB doesn't work (hangs at "Combining exe+phpdll") / Win 7

### ISSUE THREAD

**Issue by Kadigan** [jaredallard/phc-win#20]
If I have "EVB (One-exe)" checked, it will not produce an executable file no matter how long I wait.

I have excluded the program folder from antivirus - no change.

```
[03:05:41]: Started
[03:06:00]: Enabled EVB.
[03:06:01]: Selected 'D:/phc-win/mpcgen/mpcgen.php'

[03:06:02]: Starting compile process.
[03:06:02]: Copying file(s)
[03:06:02]: Embeding 'main.php' to PHP/RUN
[03:06:03]: Generating evp
[03:06:03]: Combining exe+phpdll
```

- and that's where it stops.

I have no error message, no log to read. If I'm missing anything, I am not told.

*Possible that this is in some way related to another issue I have - #19 - but renaming php.ini doesn't solve the problem.*

**Comment by nothrem** [comment]
Instead of using integrated EVB, you can download it from https://enigmaprotector.com/en/downloads.html (use the Freeware version)

1. run phx-win and open your PHP file
2. enable UPX (EVB can compress the DLL but not this EXE) and compile
3. run Enigma Virtual Box
4. choose the compiled EXE as the input file
5. select output file name (it's not possible to overwrite the input file, but you can place it inside a `bin` folder)
6. drag&drop the `php*ts.dll` into EVB and choose `%DEFAULT_FOLDER%`
7. under Files Options check Enable Files Virtualization and Compress Files
8. Click Process
9. Save project for repeated use by File - Save project as...

Alternatively, you may choose to place the `php*ts.dll` inside %SYSTEM FOLDER%, %PROGRAM FILES% or %AllUsers, ApplicationData FOLDER%, then click it and choose Edit - Write to Disk if not Exists. This will make the app run faster but will leave the DLL on the disk.

**Comment by kovalensky** [comment]
> Instead of using integrated EVB, you can download it from https://enigmaprotector.com/en/downloads.html (use the Freeware version)
> Alternatively, you may choose to place the `php*ts.dll` inside %SYSTEM FOLDER%, %PROGRAM FILES% or %AllUsers, ApplicationData FOLDER%, then click it and choose Edit - Write to Disk if not Exists. This will make the app run faster but will leave the DLL on the disk.

You could get rid of phc-win and use php version of your choice, here's a step by step compilation [article](https://habr.com/en/articles/727774/) for php 8.
